Create CCC-TAC-Minutes-2023-04-20.md
confidential-computing/governance pull request #166
Opened 2023-04-21 21:29 UTC by krtaylor

2023-04-24 14:39 UTC, lkatalin requested changes

2023-04-24 14:39 UTC, lkatalin commented on TAC/Meetings/2023/2023-04-20/CCC-TAC-Minutes-2023-04-20.md
> +    * Cross project integration - broadening of the description, adding or 2 upstream projects being used by more than one project
```suggestion
    * Cross project integration - LS proposed broadening of the goal description to: adding module maintained by another CCC project, or 2 upstream projects being used or contributed to by more than one project
```

2023-05-04 13:40 UTC, dcmiddle approved these changes

2023-05-04 13:54 UTC, dthaler commented on TAC/Meetings/2023/2023-04-20/CCC-TAC-Minutes-2023-04-20.md
> +* **Recordings**: [YouTube TAC Playlist](https://www.youtube.com/playlist?list=PLmfkUJc39uMjaB\_I1dYW72I44kr9QzG\_B)
This link doesn't seem to work for me.  Is it just me?

2023-05-04 13:54 UTC, dthaler commented on TAC/Meetings/2023/2023-04-20/CCC-TAC-Minutes-2023-04-20.md
> +    * KT brought up the possibility of at CCS of setting up regular project maintainer meetings, Lily to follow up with the EUAC and Outreach chairs for event presence
Should "Lily to follow up..." be listed as an `**ACTION**`?

2023-05-04 14:24 UTC, dthaler commented on TAC/Meetings/2023/2023-04-20/CCC-TAC-Minutes-2023-04-20.md
> +* **Recordings**: [YouTube TAC Playlist](https://www.youtube.com/playlist?list=PLmfkUJc39uMjaB\_I1dYW72I44kr9QzG\_B)
```suggestion
* **Recordings**: [YouTube TAC Playlist](https://www.youtube.com/playlist?list=PLmfkUJc39uMjaB_I1dYW72I44kr9QzG_B)
```

2023-05-04 15:03 UTC, dthaler approved these changes

2023-05-04 15:33 UTC, yashkmankad commented
Approved.

(While I wait for the CODEOWNERS issue to get resolved)

2023-05-05 18:09 UTC, merged