Update CODEOWNERS
confidential-computing/governance pull request #234
Opened 2024-04-18 21:52 UTC by mssun

- Add myself (Mingshen Sun) in the CODEOWNERS
- Remove @dthaler

2024-04-18 22:44 UTC, AlecFernandez requested changes
recommend removing @dthaler

2024-04-19 00:28 UTC, dcmiddle approved these changes
@Riaankl please add Mingshen to the org.

2024-04-19 02:06 UTC, dthaler approved these changes

2024-04-19 13:20 UTC, merged

2024-04-19 13:23 UTC, Riaankl commented
> @Riaankl please add Mingshen to the org.

Merge code owner file and also sent an invitation to the org