Update scoping doc from past tense to current tense
confidential-computing/governance pull request #62
Opened 2020-08-19 20:13 UTC by dthaler

Also add other relevant orgs:
TrustedFirmware.org which has been discussed on the TAC mailing list,
and FIDO Alliance which has been discussed in the IETF as being relevant
in this space.

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

2020-08-20 09:36 UTC, MikeCamel requested changes
Good improvements, thanks.

2020-08-20 09:36 UTC, MikeCamel commented on scoping.md
> +Unfortunately, unlike the term Confidential Computing� several of
typo after "Computing"

2020-08-28 18:27 UTC, dthaler commented
@MikeCamel fixed typo, please check and approve if looks ok.

2020-10-16 07:22 UTC, spjohnso requested changes
Some of section 2 on fine grained questions is still written in the past tense:

for instance: the "TAC has the consensus to recommend", or
"All five of these are strategy questions fort he board to answer..."

2020-10-17 01:07 UTC, dthaler commented
@spjohnso Updated section 2, please check

2020-10-17 17:54 UTC, spjohnso approved these changes

2020-10-17 21:10 UTC, dthaler commented
Time bomb expires October 24 or when a third TAC member approves

2020-10-26 21:55 UTC, dthaler commented
Merging per time bomb expiry

2020-10-26 21:55 UTC, merged